
export const ADD_WIDGET_BLOCKS = 'ADD_WIDGET_BLOCKS';
export const REMOVE_WIDGET_BLOCKS = 'REMOVE_WIDGET_BLOCKS';
export const REORDER_WIDGET_BLOCKS = 'REORDER_WIDGET_BLOCKS';
export const UPDATE_WIDGET_BLOCKS = 'UPDATE_WIDGET_BLOCKS';
export const CHECK_WIDGET_BLOCKS = 'CHECK_WIDGET_BLOCKS';
export const SET_WIDGET_BLOCKS = 'SET_WIDGET_BLOCKS';

export const ADD_TAG = 'ADD_TAG';

export const CHANGE_FOR_SALES = 'CHANGE_FOR_SALES';

export const SET_TITLE = 'SET_TITLE';

export const SET_BODY_COLOR = 'SET_BODY_COLOR';

export const ADD_HTML = 'ADD_HTML';
export const CREATE_EDITORS = 'CREATE_EDITORS';


export const DELETE_RANGE = 'DELETE_RANGE';
export const SAVE_RANGE = 'SAVE_RANGE';
export const GET_RANGE = 'GET_RANGE';

export const SAVE_ELEM = 'SAVE_ELEM';
export const GET_ELEM = 'GET_ELEM';

export const RESTORE_RANGE = 'RESTORE_RANGE';
export const SET_TYPE_CURSOR = 'SET_TYPE_CURSOR';

export const CLOSE_POPUP = 'CLOSE_POPUP';
export const OPEN_POPUP = 'OPEN_POPUP';
export const CHANGE_STEP_POPUP = 'CHANGE_STEP_POPUP';
export const CHANGE_TITLE_POPUP = 'CHANGE_TITLE_POPUP';
export const SET_IMAGE_POPUP = 'SET_IMAGE_POPUP';

export const DELETE_ARRAY_IMAGE = 'DELETE_ARRAY_IMAGE';
export const ADD_ARRAY_IMAGE = 'ADD_ARRAY_IMAGE';
export const UPDATE_ARRAY_IMAGE = 'UPDATE_ARRAY_IMAGE';
export const SET_ARRAY_IMAGE = 'SET_ARRAY_IMAGE';
